### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by danielochuba**
# Setup Leaderboard project
## Markup wireframe, to display names and scores

### CODE REVIEW

**Review by amejid — COMMENTED** [review]
Hi @danielochuba, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional README file. Please you the [template](https://github.com/microverseinc/readme-template) and customize it to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by aamirkhan2478 — APPROVED** [review]
Hi @danielochuba , 

GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] Well done :+1:  you did very nice work but please edit your `branch name`. Your `branch name` is not descriptive the `branch name` should be any feature or action like `setup-project` please edit your branch name here is the [video](https://www.youtube.com/watch?v=LYJ81OKXH9c) watch this video and edit your branch. This is `optional` but recommended so kindly don't skip this requirement and also next time please use descriptive branch names. :slightly_smiling_face: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danielochuba** [comment]
@aamirkhan2478 that's a great suggestion, thanks a lot I'll  keep that in mind from now onwards ✔

**Comment by aamirkhan2478** [comment]
> @aamirkhan2478 that's a great suggestion, thanks a lot I'll keep that in mind from now onwards heavy_check_mark

My pleasure :slightly_smiling_face:

**Pull request merged**
